# Generated by Django 3.0.3 on 2021-03-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bg_image',
            field=models.ImageField(blank=True, null=True, upload_to='bgimage/', verbose_name='Backgroung Image'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fb_link',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/', verbose_name='Icon Image'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ig_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='introduction',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tw_link',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter Link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'This Username already exists.'}, help_text='Required 30 characters or fewer.', max_length=30, unique=True, verbose_name='username'),
        ),
    ]
